#!/bin/bash

set -e
set -x

env

. /usr/share/mkapp/functions

prepare

for arch in $ARCH; do
  set_env $arch
  ant_build clean-all
  mkdir -p target/tar
  cd target/tar
  apt-get download -t ${DIST} libjava-modbus:${arch} libmodbus5:${arch}
  mv libjava-modbus_*.deb libjava-modbus.deb
  mv libmodbus5_*.deb libmodbus5.deb
  cd -
  ant_build

  if [ "$PUBLISH" ]; then
    publish_ivy ivy
    cd target/tar
    rm libjava-modbus.deb libmodbus5.deb
    dpkg-name *.deb
    publish_deb *.deb
    cd -
  fi

  if [ "$RELEASE" ]; then
    cd target
    APP=$(ls *.app)
    APP=${APP%.app}
    mv $APP.app ${APP}_${arch}.app
    zip ../${APP}_${arch}.zip ${APP}_${arch}.app
    cd -
    echo "::set-output name=APP_${arch}::${APP}_${arch}.zip"
  fi
done
